name: Test Client

on:
  workflow_call:
    inputs:
      test-script:
        required: true
        type: string
      browsers:
        required: true
        type: string
jobs:
  test:
    runs-on: ubuntu-latest
    name: ${{ matrix.browser }}
    continue-on-error: true
    strategy:
      matrix:
        browser: ${{ fromJSON(inputs.browsers) }}
    environment: test-client
    env:
      SAUCE_USERNAME: ${{ secrets.SAUCE_USERNAME }}
      SAUCE_ACCESS_KEY: ${{ secrets.SAUCE_ACCESS_KEY }}
      CLIENT_TESTS_CURRENT_BROWSER: ${{ matrix.browser }}
    outputs:
      has-error: "${{ steps.has-error.outputs.value }}"
    steps:
      - uses: DevExpress/testcafe-build-system/actions/set-status@main
        with:
          status: 'pending'
            
      - uses: actions/checkout@v3
        with:
          ref: ${{github.event.inputs.merged_sha || github.event.inputs.sha}}

      - uses: actions/setup-node@v3
        with:
          node-version: 16

      - uses: DevExpress/testcafe-build-system/actions/read-artifacts@main
        with:
          package-name: 'testcafe'

      - name: Get npm cache directory
        id: npm-cache-dir
        run: |
          echo "dir=$(npm config get cache)" >> $GITHUB_OUTPUT
      - uses: actions/cache@v3
        with:
          path: ${{ steps.npm-cache-dir.outputs.dir }}
          key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-node-
      - run: npm ci

      - run: ${{ inputs.test-script }}
        timeout-minutes: 60

      - name: Has error
        id: has-error
        if: failure() || cancelled()
        shell: bash
        run: echo "value=true" >> "$GITHUB_OUTPUT"
    
  set-result-status:
    if: always()
    needs: test
    runs-on: ubuntu-latest
    steps:
      - uses: DevExpress/testcafe-build-system/actions/set-status@main
        with:
          status: ${{ needs.test.outputs.has-error && 'failure' || 'success' }}

      - name: Exit with error
        if: ${{ needs.test.outputs.has-error }}
        run: exit 1